### ISSUE TITLE
Composer bug

### ISSUE THREAD

**Issue by AIPTU** [Muqsit/SimplePacketHandler#13]
Problem 1
    - Root composer.json requires muqsit/simple-packet-handler ^0.1.3 -> satisfiable by muqsit/simple-packet-handler[0.1.3].
    - muqsit/simple-packet-handler 0.1.3 requires pocketmine/pocketmine-mp ^4.0.0 -> found pocketmine/pocketmine-mp[4.0.0, ..., 4.26.0] but it conflicts with your root composer.json require (^5.15).

**Comment by AIPTU** [comment]
Please tag new release

**Comment by Muqsit** [comment]
@AIPTU Just tagged v0.1.4. Could you try it and see if it address the issue?
![Screenshot_20240614_135009_Chrome](https://github.com/Muqsit/SimplePacketHandler/assets/15074389/865e8289-9299-4c21-aac4-2352201fddee)

**Comment by AIPTU** [comment]
Alright it's good
