### ISSUE TITLE
SimplePacket Issue

### ISSUE THREAD

**Issue by Octqne** [Muqsit/SimplePacketHandler#6]
`[00:54:01.598] [Server thread/CRITICAL]: InvalidArgumentException: "Closure must satisfy signature (pocketmine\network\mcpe\protocol\ClientboundPacket, pocketmine\network\mcpe\NetworkSession) : bool" (EXCEPTION) in "plugins/CORE/src/muqsit/simplepackethandler/utils/Utils" at line 47`

**Comment by Muqsit** [comment]
Can you send the complete backtrace along with the code snippet?

**Comment by Zqko** [comment]
whats a code snippet

**Comment by Zqko** [comment]
> Can you send the complete backtrace along with the code snippet?

InvalidArgumentException: "Closure must satisfy signature (pocketmine\network\mcpe\protocol\ClientboundPacket, pocketmine\network\mcpe\NetworkSession) : bool" (EXCEPTION) in "plugins/CORE/src/muqsit/simplepackethandler/utils/Utils" at line 48
--- Stack trace ---
  #0 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(31): muqsit\simplepackethandler\utils\Utils::parseClosureSignature(object Closure#142109, array[2], string[4] bool)
  #1 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(80): muqsit\simplepackethandler\interceptor\PacketInterceptorListener::getPidFromHandler(object Closure#142109, string[50] pocketmine\network\mcpe\protocol\ClientboundPacket)
  #2 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptor(24): muqsit\simplepackethandler\interceptor\PacketInterceptorListener->interceptOutgoing(object Closure#142109)
  #3 plugins/CORE.phar/src/CortexPE/CORE/module/AntiGlitching(38): muqsit\simplepackethandler\interceptor\PacketInterceptor->interceptOutgoing(object Closure#142109)
  #4 plugins/CORE/src/CortexPE/CORE/module/ModuleManager(101): CortexPE\CORE\module\AntiGlitching->onInitialize()
  #5 plugins/CORE/src/CortexPE/CORE/Main(40): CortexPE\CORE\module\ModuleManager->enableModules()
  #6 pmsrc/src/plugin/PluginBase(118): CortexPE\CORE\Main->onEnable()
  #7 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #8 pmsrc/src/Server(1417): pocketmine\plugin\PluginManager->enablePlugin(object CortexPE\CORE\Main#120173)
  #9 pmsrc/src/Server(1030): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21901)
  #10 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #11 pmsrc/src/PocketMine(362): pocketmine\server()
  #12 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Muqsit** [comment]
> ```
> 
> InvalidArgumentException: "Closure must satisfy signature (pocketmine\network\mcpe\protocol\ClientboundPacket, pocketmine\network\mcpe\NetworkSession) : bool" (EXCEPTION) in "plugins/CORE/src/muqsit/simplepackethandler/utils/Utils" at line 48
> --- Stack trace ---
>   #0 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(31): muqsit\simplepackethandler\utils\Utils::parseClosureSignature(object Closure#142109, array[2], string[4] bool)
>   #1 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptorListener(80): muqsit\simplepackethandler\interceptor\PacketInterceptorListener::getPidFromHandler(object Closure#142109, string[50] pocketmine\network\mcpe\protocol\ClientboundPacket)
>   #2 plugins/CORE/src/muqsit/simplepackethandler/interceptor/PacketInterceptor(24): muqsit\simplepackethandler\interceptor\PacketInterceptorListener->interceptOutgoing(object Closure#142109)
>   #3 plugins/CORE.phar/src/CortexPE/CORE/module/AntiGlitching(38): muqsit\simplepackethandler\interceptor\PacketInterceptor->interceptOutgoing(object Closure#142109)
>   #4 plugins/CORE/src/CortexPE/CORE/module/ModuleManager(101): CortexPE\CORE\module\AntiGlitching->onInitialize()
>   #5 plugins/CORE/src/CortexPE/CORE/Main(40): CortexPE\CORE\module\ModuleManager->enableModules()
>   #6 pmsrc/src/plugin/PluginBase(118): CortexPE\CORE\Main->onEnable()
>   #7 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
>   #8 pmsrc/src/Server(1417): pocketmine\plugin\PluginManager->enablePlugin(object CortexPE\CORE\Main#120173)
>   #9 pmsrc/src/Server(1030): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21901)
>   #10 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
>   #11 pmsrc/src/PocketMine(362): pocketmine\server()
>   #12 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)```
> ```

You'll need to ask the developer of the `CORE.phar` plugin to fix the issue.
